FROM dptechnology/dflow
RUN pip install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install monty -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pymatgen -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pydflow -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install urllib3 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install dpdata -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install dargs -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install ase -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pymatgen.analysis.defects -i https://pypi.tuna.tsinghua.edu.cn/simple
