FROM dptechnology/dflow
RUN pip install pip --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install monty -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pymatgen>=2023.8.10
RUN pip install pydflow -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install urllib3 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install dpdata -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install dargs -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install ase -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pymatgen.analysis.defects>=2023.8.22
RUN pip install fpop>=0.0.7 -i https://pypi.tuna.tsinghua.edu.cn/simple
