FROM dptechnology/dflow
RUN pip install pip --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install numpy -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install monty -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pymatgen>=2023.8.10 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pymatgen.analysis.defects>=2023.8.22 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install phonopy -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install seekpath -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install dpdispatcher -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pydflow>=1.7.83 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install urllib3 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install dpdata>=0.2.13 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install dargs -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install fpop>=0.0.7 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install boto3 -i https://pypi.tuna.tsinghua.edu.cn/simple
